### ISSUE TITLE
Create commission invoices don't work

### ISSUE THREAD

**Issue by ghost** [OCA/commission#21]
If I don't "Add an item" when I create commission invoices, any Invoices were created, although there is a message that says "keep empty for invoicing all the settlements".

**Comment by pedrobaeza** [comment]
Eduardo, the code is clear: https://github.com/OCA/commission/blob/8.0/sale_commission/wizard/wizard_invoice.py#L55, so please check that the conditions are met.

If you have put your agents as employees, they're not going to be invoices (obvious, because employees are paid in the payroll - there's a todo in this task).

**Comment by ghost** [comment]
Yes, you are right, it works with external agents. Sorry.

But if you want to pay an extra amount to your internal agents (employees), is this not the correct module? Or do you have to make these "invoices" manually?

**Comment by pedrobaeza** [comment]
You can do it, marking their partner as external agent. They're not incompatible. Rename in your case external agent to "Create invoices".
