### ISSUE TITLE
agent commission per product or product category

### ISSUE THREAD

**Issue by antwertinger** [OCA/commission#44]
Is it possible to set an agents comission per product or product category?

Thanks

**Comment by pedrobaeza** [comment]
Not for now

**Comment by pedrobaeza** [comment]
I have remembered this PR that enables the feature you want: https://github.com/OCA/commission/pull/31. Please check.

**Comment by ivantodorovich** [comment]
@antwertinger I'm currently using the newly added _sale_commission_formula_ module to support this feature. You just have to create the formula that matches your requirements.

**Comment by pedrobaeza** [comment]
Why don't you just review https://github.com/OCA/commission/pull/31?

**Comment by ivantodorovich** [comment]
We use more complex rules when calculating commissions. 

Our commisions depends on the product category and on the discount made by the salesman. 
Some products (categories) have "extra" commission depending on the discount made by the salesman. 

That's why sale_commission_fomula is perfect for us, and https://github.com/OCA/commission/pull/31 isn't.

But I'll review it later so it gets merged ^^

**Comment by julienb31** [comment]
Hello everyone.
I am a newcomer to the Odoo universe, which I recently installed in my business.
I have some difficulty for setting sale_commission_formula.
I would like to create a formula that calculates the various commissions according to the category of product, but I do not know how. (Eg if the product is in category A = 5% commission / if product is in category B = 7.5% commission etc.)
The field "categ_id" products does not exist in sale.order.line or in invoice.line.
Someone could give me some ideas? :-)
Thank you

**Comment by pedrobaeza** [comment]
Closing as there are several PRs for commissions at product level.
